export const filters: { [key: string]: { value: string; translation: string; color?: string }[] } = {
    type: [
        { value: "shirts", translation: "Camisas" },
        { value: "tshirts", translation: "Camisetas" },
        { value: "blouses", translation: "Blusas" },
        { value: "tank_tops", translation: "Tops / Camisetas sin mangas" },
        { value: "pants", translation: "Pantalones" },
        { value: "jeans", translation: "Jeans" },
        { value: "shorts", translation: "Shorts" },
        { value: "dresses", translation: "Vestidos" },
        { value: "skirts", translation: "Faldas" },
        { value: "jackets", translation: "Chaquetas" },
        { value: "coats", translation: "Abrigos" },
        { value: "suits", translation: "Trajes" },
        { value: "blazers", translation: "Blazers" },
        { value: "hoodies", translation: "Sudaderas" },
        { value: "sweaters", translation: "Jerséis / Suéteres" },
        { value: "cardigans", translation: "Cárdigans" },
        { value: "vests", translation: "Chalecos" },
        { value: "overalls", translation: "Monos / Overoles" },
        { value: "jumpsuits", translation: "Enterizos" },
        { value: "leggings", translation: "Leggings" },
        { value: "sweatpants", translation: "Pantalones deportivos" },
        { value: "tracksuits", translation: "Chándales" },
        { value: "pajamas", translation: "Pijamas" },
        { value: "bathrobes", translation: "Batas" },
        { value: "underwear", translation: "Ropa interior" },
        { value: "bras", translation: "Sujetadores" },
        { value: "panties", translation: "Bragas" },
        { value: "boxers", translation: "Boxers" },
        { value: "briefs", translation: "Calzoncillos" },
        { value: "socks", translation: "Calcetines" },
        { value: "stockings", translation: "Medias" },
        { value: "tights", translation: "Leotardos" },
        { value: "swimwear", translation: "Ropa de baño" },
        { value: "bikinis", translation: "Bikinis" },
        { value: "one_piece_swimsuit", translation: "Bañadores de una pieza" },
        { value: "boardshorts", translation: "Bañadores de hombre" },
        { value: "sandals", translation: "Sandalias" },
        { value: "shoes", translation: "Zapatos" },
        { value: "boots", translation: "Botas" },
        { value: "sneakers", translation: "Zapatillas deportivas" },
        { value: "loafers", translation: "Mocasines" },
        { value: "heels", translation: "Tacones" },
        { value: "slippers", translation: "Zapatillas de estar en casa" },
        { value: "flip_flops", translation: "Chanclas" },
        { value: "sportswear", translation: "Ropa deportiva" },
        { value: "cycling_wear", translation: "Ropa de ciclismo" },
        { value: "yoga_wear", translation: "Ropa de yoga" },
        { value: "hiking_wear", translation: "Ropa de senderismo" },
        { value: "gloves", translation: "Guantes" },
        { value: "hats", translation: "Sombreros / Gorros" },
        { value: "scarves", translation: "Bufandas" },
        { value: "belts", translation: "Cinturones" },
        { value: "ties", translation: "Corbatas" }
    ],
    color: [
        { value: "red", translation: "Rojo", color: "rgb(255, 0, 0)" },
        { value: "blue", translation: "Azul", color: "rgb(0, 0, 255)" },
        { value: "green", translation: "Verde", color: "rgb(0, 128, 0)" },
        { value: "black", translation: "Negro", color: "rgb(0, 0, 0)" },
        { value: "white", translation: "Blanco", color: "rgb(255, 255, 255)" },
        { value: "yellow", translation: "Amarillo", color: "rgb(255, 255, 0)" },
        { value: "orange", translation: "Naranja", color: "rgb(255, 165, 0)" },
        { value: "pink", translation: "Rosa", color: "rgb(255, 192, 203)" },
        { value: "purple", translation: "Morado", color: "rgb(128, 0, 128)" },
        { value: "gray", translation: "Gris", color: "rgb(128, 128, 128)" },
        { value: "brown", translation: "Marrón", color: "rgb(139, 69, 19)" },
        { value: "beige", translation: "Beige", color: "rgb(245, 245, 220)" },
        { value: "turquoise", translation: "Turquesa", color: "rgb(64, 224, 208)" },
        { value: "lilac", translation: "Lila", color: "rgb(200, 162, 200)" },
        { value: "gold", translation: "Dorado", color: "rgb(255, 215, 0)" },
        { value: "silver", translation: "Plateado", color: "rgb(192, 192, 192)" },
    ],
    size: [
        { value: "xxs", translation: "XXS" },
        { value: "xs", translation: "XS" },
        { value: "s", translation: "S" },
        { value: "m", translation: "M" },
        { value: "l", translation: "L" },
        { value: "xl", translation: "XL" },
        { value: "xxl", translation: "XXL" },
    ],
    section: [
        { value: "woman", translation: "Mujeres" },
        { value: "man", translation: "Hombres" },
        { value: "kids", translation: "Niños" },
    ],
    brand: [
        { value: "nike", translation: "Nike" },
        { value: "adidas", translation: "Adidas" },
        { value: "zara", translation: "Zara" },
        { value: "hm", translation: "H&M" },
        { value: "levis", translation: "Levi's" },
        { value: "puma", translation: "Puma" },
        { value: "mango", translation: "Mango" },
        { value: "bershka", translation: "Bershka" },
        { value: "stradivarius", translation: "Stradivarius" },
        { value: "pullbear", translation: "Pull&Bear" },
        { value: "primark", translation: "Primark" },
        { value: "desigual", translation: "Desigual" },
        { value: "massimo_dutti", translation: "Massimo Dutti" },
        { value: "calvin_klein", translation: "Calvin Klein" },
        { value: "tommy_hilfiger", translation: "Tommy Hilfiger" },
        { value: "guess", translation: "Guess" },
        { value: "lacoste", translation: "Lacoste" },
        { value: "new_balance", translation: "New Balance" },
        { value: "reebok", translation: "Reebok" },
        { value: "under_armour", translation: "Under Armour" },
        { value: "timberland", translation: "Timberland" },
        { value: "north_face", translation: "North Face" },
        { value: "gucci", translation: "Gucci" },
        { value: "prada", translation: "Prada" },
        { value: "armani", translation: "Armani" },
        { value: "dolce_gabbana", translation: "Dolce & Gabbana" },
        { value: "versace", translation: "Versace" },
        { value: "fendi", translation: "Fendi" },
        { value: "balenciaga", translation: "Balenciaga" },
        { value: "valentino", translation: "Valentino" },
        { value: "hermes", translation: "Hermès" },
    ],
};

// Funció per obtenir la traducció per categoria i valor
export const getTranslation = (category: string, value: string): string | undefined => {
    const categoryFilters = filters[category];
    if (!categoryFilters) return undefined;

    const foundItem = categoryFilters.find(item => item.value === value);
    return foundItem ? foundItem.translation : undefined;
};