const filters: { [key: string]: string[] } = {
    type: [
        "Camisas",
        "Pantalones",
        "Vestidos",
        "Chaquetas",
        "Faldas",
        "Sudaderas",
        "Camisetas",
        "Jeans",
        "Abrigos",
        "Trajes",
        "Ropa interior",
        "Zapatos",
        "Sandalias",
        "Botas",
        "Calcetines",
        "Pijamas",
        "Ropa deportiva",
    ],
    color: [
        "Rojo",
        "Azul",
        "Verde",
        "Negro",
        "Blanco",
        "Amarillo",
        "Naranja",
        "Rosa",
        "Morado",
        "Gris",
        "Marrón",
        "Beige",
        "Turquesa",
        "Lila",
        "Dorado",
        "Plateado",
    ],
    brand: [
        "Nike",
        "Adidas",
        "Zara",
        "H&M",
        "Levi's",
        "Puma",
        "Mango",
        "Bershka",
        "Stradivarius",
        "Pull&Bear",
        "Primark",
        "Desigual",
        "Massimo Dutti",
        "Calvin Klein",
        "Tommy Hilfiger",
        "Guess",
        "Lacoste",
        "New Balance",
        "Reebok",
        "Under Armour",
        "Timberland",
        "North Face",
        "Gucci",
        "Prada",
        "Armani",
        "Dolce & Gabbana",
        "Versace",
        "Fendi",
        "Balenciaga",
        "Valentino",
        "Hermès",
    ],
};

export default filters;
