const filters: { [key: string]: { value: string; translation: string; color?: string }[] } = {
    type: [
        { value: "shirts", translation: "Camisas" },
        { value: "pants", translation: "Pantalones" },
        { value: "dresses", translation: "Vestidos" },
        { value: "jackets", translation: "Chaquetas" },
        { value: "skirts", translation: "Faldas" },
        { value: "hoodies", translation: "Sudaderas" },
        { value: "tshirts", translation: "Camisetas" },
        { value: "jeans", translation: "Jeans" },
        { value: "coats", translation: "Abrigos" },
        { value: "suits", translation: "Trajes" },
        { value: "underwear", translation: "Ropa interior" },
        { value: "shoes", translation: "Zapatos" },
        { value: "sandals", translation: "Sandalias" },
        { value: "boots", translation: "Botas" },
        { value: "socks", translation: "Calcetines" },
        { value: "pajamas", translation: "Pijamas" },
        { value: "sportswear", translation: "Ropa deportiva" },
    ],
    color: [
        { value: "red", translation: "Rojo", color: "rgb(255, 0, 0)" },
        { value: "blue", translation: "Azul", color: "rgb(0, 0, 255)" },
        { value: "green", translation: "Verde", color: "rgb(0, 128, 0)" },
        { value: "black", translation: "Negro", color: "rgb(0, 0, 0)" },
        { value: "white", translation: "Blanco", color: "rgb(255, 255, 255)" },
        { value: "yellow", translation: "Amarillo", color: "rgb(255, 255, 0)" },
        { value: "orange", translation: "Naranja", color: "rgb(255, 165, 0)" },
        { value: "pink", translation: "Rosa", color: "rgb(255, 192, 203)" },
        { value: "purple", translation: "Morado", color: "rgb(128, 0, 128)" },
        { value: "gray", translation: "Gris", color: "rgb(128, 128, 128)" },
        { value: "brown", translation: "Marrón", color: "rgb(139, 69, 19)" },
        { value: "beige", translation: "Beige", color: "rgb(245, 245, 220)" },
        { value: "turquoise", translation: "Turquesa", color: "rgb(64, 224, 208)" },
        { value: "lilac", translation: "Lila", color: "rgb(200, 162, 200)" },
        { value: "gold", translation: "Dorado", color: "rgb(255, 215, 0)" },
        { value: "silver", translation: "Plateado", color: "rgb(192, 192, 192)" },
    ],
    size: [
        { value: "2xs", translation: "2XS" },
        { value: "xs", translation: "XS" },
        { value: "s", translation: "S" },
        { value: "m", translation: "M" },
        { value: "l", translation: "L" },
        { value: "xl", translation: "XL" },
        { value: "xxl", translation: "2XL" },
    ],
    material: [
        { value: "cotton", translation: "Cotton" },
        { value: "linen", translation: "Linen" },
        { value: "wool", translation: "Wool" },
        { value: "leather", translation: "Leather" },
        { value: "polyester", translation: "Polyester" },
        { value: "silk", translation: "Silk" },
        { value: "denim", translation: "Denim" },
        { value: "nylon", translation: "Nylon" },
        { value: "rayon", translation: "Rayon" },
        { value: "spandex", translation: "Spandex" },
    ],
    print: [
        { value: "solid", translation: "Solid" },
        { value: "striped", translation: "Striped" },
        { value: "checked", translation: "Checked" },
        { value: "floral", translation: "Floral" },
        { value: "plaid", translation: "Plaid" },
        { value: "polka_dots", translation: "Polka Dots" },
        { value: "camouflage", translation: "Camouflage" },
        { value: "animal_print", translation: "Animal Print" },
        { value: "graphic", translation: "Graphic" },
        { value: "paisley", translation: "Paisley" },
    ],
    section: [
        { value: "woman", translation: "Mujeres" },
        { value: "man", translation: "Hombres" },
        { value: "kids", translation: "Niños" },
    ],
    brand: [
        { value: "nike", translation: "Nike" },
        { value: "adidas", translation: "Adidas" },
        { value: "zara", translation: "Zara" },
        { value: "hm", translation: "H&M" },
        { value: "levis", translation: "Levi's" },
        { value: "puma", translation: "Puma" },
        { value: "mango", translation: "Mango" },
        { value: "bershka", translation: "Bershka" },
        { value: "stradivarius", translation: "Stradivarius" },
        { value: "pullbear", translation: "Pull&Bear" },
        { value: "primark", translation: "Primark" },
        { value: "desigual", translation: "Desigual" },
        { value: "massimo_dutti", translation: "Massimo Dutti" },
        { value: "calvin_klein", translation: "Calvin Klein" },
        { value: "tommy_hilfiger", translation: "Tommy Hilfiger" },
        { value: "guess", translation: "Guess" },
        { value: "lacoste", translation: "Lacoste" },
        { value: "new_balance", translation: "New Balance" },
        { value: "reebok", translation: "Reebok" },
        { value: "under_armour", translation: "Under Armour" },
        { value: "timberland", translation: "Timberland" },
        { value: "north_face", translation: "North Face" },
        { value: "gucci", translation: "Gucci" },
        { value: "prada", translation: "Prada" },
        { value: "armani", translation: "Armani" },
        { value: "dolce_gabbana", translation: "Dolce & Gabbana" },
        { value: "versace", translation: "Versace" },
        { value: "fendi", translation: "Fendi" },
        { value: "balenciaga", translation: "Balenciaga" },
        { value: "valentino", translation: "Valentino" },
        { value: "hermes", translation: "Hermès" },
    ],
};

export default filters;
